name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Lint with ruff (errors)
      uses: chartboost/ruff-action@v1
      with:
        version: 0.0.255
        args: --format=github --select=E9,F7,F63,F82 --show-source

    - name: Lint with ruff (warnings)
      uses: chartboost/ruff-action@v1
      with:
        version: 0.0.255
        args: --exit-zero

    - name: Check formatting with black
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        version: "~=23.0"
